openapi: "3.0.1"
info:
  title: "Queue Based Leveling Example"
  version: "2021-03-31 17:32:29UTC"
paths:
  /submit:
    post:
      responses:
        default:
          description: "Response for POST /"
      x-amazon-apigateway-integration:
        type: "aws"
        uri: "arn:aws:apigateway:${AWS::Region}:MySqsQueue.sqs:action/SendMessage"
          #Fn::Sub: !GetAtt MySqsQueue.Arn
          #Fn::Sub: "arn:aws:apigateway:${AWS::Region}:events:action/SendMessage"
        #integrationSubtype: "SQS-SendMessage"
        credentials:
          Fn::GetAtt: [MyApiRole, Arn]
        httpMethod: "POST"
        connectionType: "INTERNET"
        payloadFormatVersion: "1.0"
        requestParameters:
          MessageBody: "$request.body"
          QueueUrl:
            Ref: MySqsQueue

x-amazon-apigateway-cors:
  allowMethods:
  - "*"
  maxAge: 0
  allowCredentials: false
  allowOrigins:
  - "*"
x-amazon-apigateway-importexport-version: "1.0"