version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sqs-test-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-16zyvgrbkywqn"
s3_prefix = "sqs-test-app"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
